site_name: fastapi-structlog
site_description: Structured logs and middleware for fastapi with sentry integration
site_url: https://github.com/redb0/fastapi-logger
repo_name: redb0/fastapi-logger
repo_url: https://github.com/redb0/fastapi-logger

theme:
  name: material
  # custom_dir: docs/overrides
  palette:
  - scheme: default
    primary: deep purple
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: deep purple
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  # - navigation.tabs
  # icon:
  #   repo: fontawesome/brands/github-alt
  # logo: img/icon-white.svg
  # favicon: img/favicon.png
  language: ru

nav:
  - index.md
  - log_in_console.md
  - log_in_file.md
  - log_in_db.md
  - syslog.md
  - middleware.md
  - sentry.md
  - contributing.md
  - release-notes.md